markdown: rdiscount
permalink: /:year/:month/:day/:title/
url: http://huangtuzhi.github.com
highlighter: pygments
safe: true
paginate: 16
auto: true
github: Huangtuzhi

# 插件
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap